name: proteingraph-dev
channels:
- conda-forge
dependencies:
- python>=3.6
- biopandas
- black>=19.3b0
- bumpversion>=0.5.3
- flake8
- isort>=4.3.21
- jupyter>=1.0.0
- jupyterlab>=1.1.4
- mypy
- networkx>=2.3
- numpy>=1.17.2
- pandas>=0.25.1
- pydocstyle>=5.0.0
- pylint>=2.4.2
- pyprojroot>=0.2.0
- pytest-cov
- pytest-xdist>=1.29.0
- pytest>=5.2.0
- scikit-learn>=0.21.3
- scipy>=1.3.1
- twine>=2.0.0
- xarray
